all:
  children:
    media_servers:
      hosts:
        photos:
          ansible_host: 192.168.50.130  # Your Immich LXC IP
          ansible_user: root
          ansible_port: 22
          
          # EPS Specific Variables
          immich_compose_path: "/opt/stacks/immich"
          photoprism_compose_path: "/opt/stacks/photoprism"
          
          # Timing Configuration
          immich_processing_start: "11:00"
          immich_processing_end: "13:00"
          photoprism_processing_start: "13:05"
          photoprism_processing_end: "10:55"